### ISSUE TITLE
more features

### ISSUE THREAD

**Issue by jeffgran** [rundmt/react-native-flexbox-grid#10]
This is a cool little library!

I am thinking about using it to replace my use of `react-bootstrap`'s Row and Col, in a project where I would like to move to using `react-native-web` so my components can be rendered both in web and in react-native. I just did a little experiment and this does work with react-native web.

Two things I am thinking of adding:

- `Dimensions.addEventListener` -- so we can have a truly responsive grid when rotating a device or changing window size in web.
- making the breakpoints configurable, like maybe you'd just specify an object like `{sm: 768, myBreakpoint: 999}` and it would set up all the props and everything for you based on those, or just use the existing defaults if you don't specify.

Just curious if you'd be open to accepting a pull request for either or both of those additions?

**Comment by rundmt** [comment]
Hi @jeffgran, sorry about the delayed response. I haven't had much time to work on this project.  I think your ideas are great, and if you make a PR I will review it and look at the changes when I get a chance. 

A better option is another project that's based on this project. It has quite a few more features and is way more active. https://github.com/idibidiart/react-native-responsive-grid. I'm not sure if that project would be open to your feature requests, but I think your contributions there would have a much bigger reach.

**Comment by idibidiart** [comment]
Hey Derek,

Just a note to say I'm very grateful for the work you had done here. 

I found react-native-flexbox-grid while working under deadline pressure on a project for a major client. Working with raw Flexbox was very time consuming. I found your work to be extremely helpful as a core to build around.  

I've just updated aspectRatio support so that it matches images to the nearest known aspect ratio, and I've adding support for alignContent for wrapped content within rows which was introduced in RN 0.43. 

I have a major client using it and so the API is now stable and changes will likely be backward compatible form this point on, but no absolute guarantee on that yet, as it's only one month old!

@jeffgran  you don't need to get low level to get a truly responsive grid ... the grid should react on layout changes and update automatically. This is already done in the version @rundmt  referenced.

As far as making breakpoints configurable, I'd like to do that and also make the set of supported aspect ratios configurable (and if too many then use binary search to find nearest match) -- happy to work on those next.

@rundmt ^

**Comment by idibidiart** [comment]
@jeffgran 

breakPoints demo: 

https://www.youtube.com/watch?v=GZ1uxWEVAuQ

**Comment by jeffgran** [comment]
@rundmt Thanks for the tip, I'll look at the other project.

@idibidiart nice. This may sound strange but I'm actually not even planning on trying to use this project in React Native (yet) -- just wanting to start building a web app using react-native-web with a flexbox layout that will be compatible with RN when we decide to build a RN app at a later date.

Have you given any thought to supporting the web case too? Maybe if I was going to dedicate some time to this, that would be where I could contribute?

(should we move this discussion to react-native-responsive-grid?)

**Comment by jeffgran** [comment]
PS Here is the commit where I added web-compatibility and responsiveness to the fork of this project, in case you're interested to see (either of you): https://github.com/trelora/react-native-flexbox-grid/commit/a2d753e5663cdbd503b0d6aed6701676beca23ab

**Comment by idibidiart** [comment]
@jeffgran that is exactly my plan. The next step is to make it work for ReactJS then React Native Web and React Native Windows. I know the things that need to change in case of ReactJS but have yet to looking into the required changes for React Native Web and React Native Windows.

I did add layoutEvent to support tapping into layout changes at any row node in the component subtree (the row component being the container to column components and the one responsible for rendering and re-rendering them) But the developer does not need to do anything special for responsive behavior, only for cases where you have to decide with custom imperative logic (as opposed to declaratively using the grid) what and how to render based on layout changes 

Before supporting ReactJS, I have to take care of people complaining about the in-depth Readme being too long by re-organizing into easily accessible comtent. I am thinking of using readthedocs.com for that purpose.

Yes, let's take the discussion there. Thanks.

Marc
